version: '3.8'

services:
  # Test database
  testdb:
    image: postgres:12
    container_name: testpostgres
    env_file:
      - ./envs/.env.test    
    environment:
      POSTGRES_DB: test_db # Ensure the database is created
    ports:
      - "5432:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - test_network

  # Test runner
  test-runner:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.test
    env_file:
      - ./envs/.env.test    
    depends_on:
      testdb:
        condition: service_healthy
    volumes:
      - ./tests:/app/tests
      - /:/app/
      - test_coverage:/app/coverage
    networks:
      - test_network

networks:
  test_network:
    driver: bridge

volumes:
  test_db_data:
  test_coverage:
