FROM python:3.13-slim-bookworm

WORKDIR /src

# Install system dependencies and upgrade packages to reduce vulnerabilities
RUN apt-get update && apt-get install --no-install-recommends -y \
        build-essential \
        curl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy requirements first for better caching
ADD https://astral.sh/uv/install.sh /install.sh
RUN chmod -R 755 /install.sh && /install.sh && rm /install.sh

# Set up the UV environment path correctly
ENV PATH="/root/.local/bin:${PATH}"

# Copy source codes
COPY ../ .

ENV PYTHONPATH=/app
ENV TESTING=1

RUN uv sync
# Run tests by default
CMD ["uv","run","pytest", "-v", "--tb=short"]
