name: Format Project

on:
  push:
    branches:
      - "master"

jobs:
  format:
    name: Check Ruff Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Run Ruff Formatter Check
        run: |
          uv run ruff format --check .
          uv run ruff check --fix --diff .
